version: 0.2

frontend:
  phases:
    preBuild:
      commands:
        - echo Entered the preBuild phase...
        - pnpm install
    build:
      commands:
        - echo Entered the build phase...
        - pnpm run build
  artifacts:
    baseDirectory: dist
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*